[package]
name = "business-report"
version = "0.1.0"
entrypoint = "main.typ"
authors = ["Gareth Webber <https://www.garethwebber.com>"]
license = "Apache-2.0"
disciplnes = ["Business"]
description = "Multi-chapter business report with tables, infobox, author cutout."
repository = "https://github.com/garethwebber/business-report"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "report-v0.2.png"
